spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daangndb
    username: ${LOCALHOST_MYSQL_USER}
    password: ${LOCALHOST_MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  aop: # JDK Dynamic Proxy
#    proxy-target-class: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_ID}
            clientSecret: ${GOOGLE_OAUTH_PW}
            scope:
              - email
              - profile

server:
  servlet:
    encoding:
      force-response: true

mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
    secret: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG